#!/usr/bin/env bash
# Echolot installer for Linux Mint / Ubuntu / Debian.
#
# Checks the few things Echolot needs, writes the autostart entry and a launcher
# for the application menu. Nothing is compiled and no virtual environment is
# created: Echolot runs on the system Python with the GTK bindings that Cinnamon
# already ships.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_ID="echolot"
APP_NAME="Echolot"
AUTOSTART_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/autostart"
LAUNCHER_DIR="$HOME/.local/share/applications"
ICON="$ROOT/resources/$APP_ID-idle.svg"
PYTHON="$(command -v python3 || true)"

ok()   { printf '  \033[32mok\033[0m    %s\n' "$1"; }
warn() { printf '  \033[33mfehlt\033[0m %s\n' "$1"; }
fail() { printf '  \033[31mFEHLER\033[0m %s\n' "$1"; }

echo "$APP_NAME einrichten"
echo

missing_packages=()

if [[ -z "$PYTHON" ]]; then
  fail "python3 nicht gefunden"
  exit 1
fi
ok "python3 ($("$PYTHON" --version 2>&1))"

if "$PYTHON" - <<'PY' >/dev/null 2>&1
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk
PY
then
  ok "GTK-3-Bindings (python3-gi)"
else
  warn "GTK-3-Bindings"
  missing_packages+=("python3-gi" "gir1.2-gtk-3.0")
fi

if command -v ffmpeg >/dev/null 2>&1; then
  ok "ffmpeg"
else
  warn "ffmpeg (Kodierung der Aufnahme)"
  missing_packages+=("ffmpeg")
fi

if command -v parec >/dev/null 2>&1; then
  ok "parec"
else
  warn "parec (Aufnahme von Mikrofon und Ausgabe)"
  missing_packages+=("pulseaudio-utils")
fi

if command -v pactl >/dev/null 2>&1; then
  ok "pactl"
else
  warn "pactl (Geräteerkennung)"
  missing_packages+=("pulseaudio-utils")
fi

if [[ ${#missing_packages[@]} -gt 0 ]]; then
  # shellcheck disable=SC2207
  unique=($(printf '%s\n' "${missing_packages[@]}" | sort -u))
  echo
  echo "Es fehlen Pakete: ${unique[*]}"
  if command -v apt >/dev/null 2>&1; then
    read -r -p "Jetzt mit sudo apt install nachinstallieren? [j/N] " answer
    if [[ "$answer" =~ ^[jJyY]$ ]]; then
      sudo apt update && sudo apt install -y "${unique[@]}" || {
        fail "Installation fehlgeschlagen"
        exit 1
      }
    else
      echo "Übersprungen. Manuell: sudo apt install ${unique[*]}"
    fi
  else
    echo "Manuell installieren: ${unique[*]}"
  fi
fi

echo
mkdir -p "$AUTOSTART_DIR" "$LAUNCHER_DIR"

ICON_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor/scalable/apps"
mkdir -p "$ICON_DIR"
cp "$ROOT/resources/$APP_ID-idle.svg" "$ICON_DIR/$APP_ID.svg"
ok "Icon: $ICON_DIR/$APP_ID.svg"
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  gtk-update-icon-cache -f -t "${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor" >/dev/null 2>&1 || true
fi

# The entries are generated by the app itself, so the installer cannot drift
# apart from it - including the localised Comment[xx] lines.
write_entry() {  # $1 = target file, $2 = --launcher for the menu entry
  ( cd "$ROOT" && "$PYTHON" -m echolot.autostart ${2:-} ) > "$1"
}

write_entry "$AUTOSTART_DIR/$APP_ID.desktop"
ok "Autostart: $AUTOSTART_DIR/$APP_ID.desktop"

write_entry "$LAUNCHER_DIR/$APP_ID.desktop" "--launcher"
ok "Startmenü: $LAUNCHER_DIR/$APP_ID.desktop"

if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$LAUNCHER_DIR" >/dev/null 2>&1
fi

echo
"$PYTHON" "$ROOT/run.py" --check
echo
echo "Fertig. Starten mit:  $PYTHON \"$ROOT/run.py\""
echo "Doppelklick auf das Tray-Icon startet und beendet die Aufnahme."
